apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiversioningv2
spec:
  selector:
    matchLabels:
      app: apiversioningv2
  replicas: 1
  template:
    metadata:
      labels:
        app: apiversioningv2
        version: v2
    spec:
      containers:
      - name: apiversioning
        image: apiversioning:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: API_VERSION
            value: /v2
---
apiVersion: v1
kind: Service
metadata:
  name: apiversioningv2
spec:
  selector:
    app: apiversioningv2
    version: v2
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: apiversioningv2
spec:
  prefix: /api-v2
  service: apiversioningv2:8080
